{"name": "Login with invalid credentials (Should FAIL)", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\n +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x0000023E0EE7F830>()\n +    where <built-in method lower of str object at 0x0000023E0EE7F830> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\n +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d282caa09d6c7540f2096da4cfd5e224\")>.current_url\n +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d282caa09d6c7540f2096da4cfd5e224\")> = <tests.test_login.TestLogin object at 0x0000023E0EA46490>.driver", "trace": "self = <tests.test_login.TestLogin object at 0x0000023E0EA46490>\n\n    @allure.title(\"Login with invalid credentials (Should FAIL)\")\n    def test_login_invalid(self):\n        login_page = LoginPage(self.driver)\n        login_page.login(\"invalidUser\", \"wrongPass\")\n>       assert \"dashboard\" in self.driver.current_url.lower()\nE       assert 'dashboard' in 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'\nE        +  where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <built-in method lower of str object at 0x0000023E0EE7F830>()\nE        +    where <built-in method lower of str object at 0x0000023E0EE7F830> = 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login'.lower\nE        +      where 'https://opensource-demo.orangehrmlive.com/web/index.php/auth/login' = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d282caa09d6c7540f2096da4cfd5e224\")>.current_url\nE        +        where <selenium.webdriver.chrome.webdriver.WebDriver (session=\"d282caa09d6c7540f2096da4cfd5e224\")> = <tests.test_login.TestLogin object at 0x0000023E0EA46490>.driver\n\ntests\\test_login.py:21: AssertionError"}, "start": 1752588636287, "stop": 1752588648955, "uuid": "55b2cce1-a5db-499c-ae18-a4099ba22fb5", "historyId": "5da0defd295c5b73991b1ce5dbbe7dd0", "testCaseId": "5da0defd295c5b73991b1ce5dbbe7dd0", "fullName": "tests.test_login.TestLogin#test_login_invalid", "labels": [{"name": "epic", "value": "Login Module"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "AnhHuy"}, {"name": "thread", "value": "5160-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}